services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  rest_api:
    build: ./rest_api
    command: bash -c "rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    entrypoint: ./entrypoint.sh
    volumes:
      - ./rest_api:/app
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  graphql_api:
    build: ./graphql_api
    command: bash -c "rails s -b 0.0.0.0"
    ports:
      - "3001:3000"
    volumes:
      - ./graphql_api:/app
    entrypoint: ./entrypoint.sh
    depends_on:
      - rest_api

  sneakers:
    build: ./rest_api
    command: bash -c "sneakers work PolicyWorker --require app/workers/policy_worker.rb"
    volumes:
      - ./rest_api:/app
    depends_on:
      - rest_api

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    healthcheck: 
      test: ["CMD", "rabbitmqctl","await_startup"]
      interval: 5s

volumes:
  rubygems:
  database:
  rabbitmq: