services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  rest_api:
    image: ruby:3.2.2
    command: bash -c "cd /app && bin/setup && rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./rest_api:/app
      - rubygems:/usr/local/bundle
    depends_on:
      postgres:
        condition: service_started

  graphql_api:
    image: ruby:3.2.2
    command: bash -c "cd /app && bin/setup && rails s -b 0.0.0.0"
    ports:
      - "3001:3000"
    volumes:
      - ./graphql_api:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - rest_api

volumes:
  rubygems:
  database: